package com.web.dao;

import com.web.dbuitl.ItemDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    int insert(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    ItemDao selectByPrimaryKey(Integer id);
    List<ItemDao> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    int updateByPrimaryKey(ItemDao record);
    int increaseSales(@Param("id") Integer id,@Param("amount") Integer amount);
}