package com.web.dbuitl;

import java.math.BigDecimal;

public class ItemDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.title
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    private double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.desciption
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    private String desciption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sales
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.image
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.title
     *
     * @return the value of item.title
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.title
     *
     * @param title the value for item.title
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.desciption
     *
     * @return the value of item.desciption
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public String getDesciption() {
        return desciption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.desciption
     *
     * @param desciption the value for item.desciption
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public void setDesciption(String desciption) {
        this.desciption = desciption == null ? null : desciption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sales
     *
     * @return the value of item.sales
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sales
     *
     * @param sales the value for item.sales
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.image
     *
     * @return the value of item.image
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.image
     *
     * @param image the value for item.image
     *
     * @mbg.generated Mon Apr 29 22:34:45 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}