package com.web.dao;

import com.web.dbuitl.ImagesDao;

import java.util.List;

public interface ImagesDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    int insert(ImagesDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    int insertSelective(ImagesDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    ImagesDao selectByPrimaryKey(Integer id);
    List<ImagesDao> list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    int updateByPrimaryKeySelective(ImagesDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    int updateByPrimaryKey(ImagesDao record);
}