package com.web.dbuitl;

public class ImagesDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.id
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.url
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.name
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.lujing
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.id
     *
     * @return the value of images.id
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.id
     *
     * @param id the value for images.id
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.url
     *
     * @return the value of images.url
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.url
     *
     * @param url the value for images.url
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.name
     *
     * @return the value of images.name
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.name
     *
     * @param name the value for images.name
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.lujing
     *
     * @return the value of images.lujing
     *
     * @mbg.generated Sat May 18 00:17:53 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}